spring:
  ai:
    mcp:
      server:
        name: hachimi-image-search-mcp-server
        version: 1.0.0
        type: SYNC
        enabled: true
        stdio: true
  main:
    web-application-type: none
    banner-mode: off