spring:
  ai:
    mcp:
      server:
        name: hachimi-image-search-mcp-server
        version: 1.0.0
        type: SYNC
        enabled: false
  main:
    web-application-type: none # ?????server???stdio??????web?
    banner-mode: off # ???banner?????????